# Generated by Django 5.2.6 on 2025-09-18 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_remove_user_groups_alter_group_members_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='db.user'),
        ),
        migrations.AlterField(
            model_name='message',
            name='referants',
            field=models.ManyToManyField(null=True, related_name='refered_in', to='db.user'),
        ),
    ]
