# Generated by Django 4.2.11 on 2025-09-24 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_message_owner_alter_message_referants'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='a', max_length=4096),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='referants',
            field=models.ManyToManyField(related_name='refered_in', to='db.user'),
        ),
    ]
