# Generated by Django 4.2.11 on 2025-09-24 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_remove_user_name_user_last_login_alter_group_members_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='null', max_length=1024),
            preserve_default=False,
        ),
    ]
