# Generated by Django 5.2.7 on 2025-11-01 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0006_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='referants',
        ),
        migrations.AddField(
            model_name='message',
            name='type',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
