# Generated by Django 5.2.7 on 2025-11-01 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0007_remove_message_referants_message_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='vibe_cl',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='group',
            name='vibe_ct',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='group',
            name='vibe_sd',
            field=models.IntegerField(default=0),
        ),
    ]
