# Generated by Django 4.2.11 on 2025-11-05 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0008_group_vibe_cl_group_vibe_ct_group_vibe_sd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='vibe_cl',
        ),
        migrations.RemoveField(
            model_name='group',
            name='vibe_ct',
        ),
        migrations.RemoveField(
            model_name='group',
            name='vibe_sd',
        ),
        migrations.AddField(
            model_name='group',
            name='main_vibe',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='group',
            name='vibes',
            field=models.JSONField(default={'cool': 0, 'ct': 0, 'sad': 0}),
        ),
    ]
