# Generated by Django 4.2.11 on 2025-11-05 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0009_remove_group_vibe_cl_remove_group_vibe_ct_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='vibes',
            field=models.JSONField(),
        ),
    ]
