# Generated by Django 4.2.11 on 2025-11-05 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0010_alter_group_vibes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='vibes',
            field=models.JSONField(default={'cool': 0, 'ct': 0, 'sad': 0}),
        ),
    ]
