# Generated by Django 4.2.11 on 2025-11-05 18:35

import db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0011_alter_group_vibes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='vibes',
            field=models.JSONField(default=db.models.default_d),
        ),
    ]
