# Generated by Django 4.2.11 on 2025-11-07 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0012_alter_group_vibes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='USERNAME_FIELD',
        ),
    ]
