# Generated by Django 4.2.11 on 2025-11-07 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0013_rename_name_user_username_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='USERNAME_FIELD',
            new_name='name',
        ),
    ]
