# Generated by Django 4.2.11 on 2025-11-13 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0014_rename_username_field_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=4294967296)),
                ('vibe', models.CharField(max_length=64)),
            ],
        ),
    ]
